### Get request
GET http://localhost:8080/app/

### Get request metrics
GET http://localhost:8080/admin/metrics

### Post reset
POST http://localhost:8080/admin/reset

### Post New User
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "mloneusk@example.co"
}

### Post New Chirp
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "dd88216a-6896-428b-aa4d-33e28565fc80"
}

### GET List Chirps
GET http://localhost:8080/api/chirps

### GET List Chirps
GET http://localhost:8080/api/chirps?author_id=sdafea